### ISSUE TITLE
Babel link mid readme leads to "You do not have access to this lesson

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/react-jsx#3]
https://learn.co/tracks/react-building-front-end-applications/meet-react/rendering/babeljs.io

this is the link

**Comment by itzsaga** [comment]
**All** the links in the markdown are being appended to the end of the lesson URL. Not sure why. Looking at the raw markdown the links are not like this. For example, what @pajamaw references is just `[Babel](babeljs.io)` in the markdown.

**Comment by itzsaga** [comment]
I learned something just now, #8 fixes this. The `http://` is missing from the links.
